name: Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_call:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: 18.13.0

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build
        run: |
          yarn build
