name: Publish

on:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:

  publish-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Fetch dependencies
        working-directory: okp4-gatsby
        run: |
          yarn --frozen-lockfile

      - name: Build
        working-directory: okp4-gatsby
        run: |
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.OKP4_TOKEN }}
          publish_dir: okp4-gatsby/public
          commit-message: |
            chore: release okp4-web github pages ${{ steps.get_version.outputs.version }}
          cname: okp4.network
