name: Publish staging

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: publish-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Fetch dependencies
        working-directory: okp4-gatsby
        run: |
          yarn --frozen-lockfile

      - name: Build
        working-directory: okp4-gatsby
        run: |
          yarn build

      - name: Replace env script
        working-directory: .github
        run: |
          cp scripts/env.staging.js ../okp4-gatsby/public/scripts/env.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.OKP4_TOKEN }}
          publish_dir: okp4-gatsby/public
          commit-message: |
            chore: deploy okp4-web github pages on staging
          cname: web-staging.okp4.network
