name: Publish production

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - id: get_latest_tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: okp4/okp4-web

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_latest_tag.outputs.tag }}

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build
        run: |
          yarn build

      - name: Replace environment config
        working-directory: .github
        run: |
          cp environments/prod/env.js ../public/scripts/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.OKP4_TOKEN }}
          publish_dir: public
          user_name: ${{ secrets.OKP4_BOT_GIT_AUTHOR_NAME }}
          user_email: ${{ secrets.OKP4_BOT_GIT_AUTHOR_EMAIL }}
          cname: okp4.network
