name: Publish

on:
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:

  publish-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Fetch dependencies
        working-directory: okp4-gatsby
        run: |
          yarn --frozen-lockfile

      - name: Build
        working-directory: okp4-gatsby
        run: |
          yarn build

      - name: Copy build output to OVH machine
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.OKP4_OVH_SSH_HOST }}
          username: ${{ secrets.OKP4_OVH_SSH_USERNAME }}
          password: ${{ secrets.OKP4_OVH_SSH_PASSWORD }}
          port: ${{ secrets.OKP4_OVH_SSH_PORT }}
          local: "okp4-gatsby/public"
          remote: "/homez.216/okpcomnvui/okp4-web"
